### ISSUE TITLE
How do I reproduce the figures in the text?

### ISSUE THREAD

**Issue by keyalone** [codyheiser/H2-tissue-labeling#14]
Fabulous work! 
   When I want to reproduce the results of Fig.4 in your article, I encounter some problems. I found your guys provided the .npynp file in the folder Figures, but i can't import the .ipynp file in the jupyter notebook and read the file as usual. Hence, is there exist convient ways to reproduce the reusults of your article?  Is there exist some errors for save the .ipynb files?

**Comment by keyalone** [comment]
I just change the .ipynp to ipynb and it's solved. Thanks for your fabulous work.

**Comment by codyheiser** [comment]
@keyalone thank you for pointing this out!  I've updated the file extensions to avoid this issue in the future.
